version: "3.7"
services:
  nginxproxy:
    image: nginx:1.20.0
    networks:
      - network
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf
      - static:/data/static
      - media:/data/media
      - /home/ubuntu/myweb:/usr/share/nginx/html
    depends_on:
      - django_gunicorn

  django_gunicorn:
    image: django-sim:1.1.1
    networks:
      - network
    volumes:
      - static:/home/sim_jango_pp/staticfiles
      - media:/home/sim_jango_pp/media



networks:
  network:

volumes:
  static:
  database:
  media:



