# Generated by Django 3.1.7 on 2022-01-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainappModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_intro', models.CharField(blank=True, max_length=255, null=True, verbose_name='메인 소개글')),
                ('project_id', models.IntegerField(verbose_name='프로젝트 index')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_image', models.TextField(blank=True, max_length=50, null=True, verbose_name='프로젝트 이미지')),
                ('project_id', models.IntegerField(verbose_name='프로젝트 index')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='프로젝트 name')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='프로젝트 정보 Category')),
                ('client', models.CharField(blank=True, max_length=100, null=True, verbose_name='프로젝트 정보 client')),
                ('project_period', models.CharField(blank=True, max_length=100, null=True, verbose_name='프로젝트 정보 project_period')),
                ('project_URL', models.CharField(blank=True, max_length=100, null=True, verbose_name='프로젝트 정보 Project_URL')),
                ('project_introduction', models.TextField(blank=True, null=True, verbose_name='프로젝트 소개')),
            ],
        ),
    ]
