# Generated by Django 3.1.7 on 2022-01-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinfomodel',
            name='project_main_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='프로젝트 대표 이미지'),
        ),
        migrations.AlterField(
            model_name='projectimagemodel',
            name='project_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='프로젝트 이미지'),
        ),
    ]
