name: ZeroDownTimeDeployTest

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: biild
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: EC2_Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          script: |
            sh deploy_pull                       

                       

